### PR TITLE
Issue #790

### PR DESCRIPTION
**Pull request by Yoric**
Ok, this one should assign a meaningful number to file descriptors.

### CODE REVIEW

**Comment by Yoric** [comment]
Mmmh... the build failure seems to be in C code. Not sure there's anything I can do about it.

**Comment by Yoric** [comment]
This is a full reimplementation, based on our earlier discussion. `dup_from`/`dup_export` is now implemented fully in the kernel and uses a `key` instead of a path to identify file descriptors.

It's still missing one pretty large bit: cleaning up file descriptors exported to a process `pid` when `pid` goes down. I haven't found where in the code we implement processes going down, but I'll try and do this in the next few days.

**Comment by Yoric** [comment]
Oh, and of course, there is the glaring absence of any test. @jackpot51, where should I put tests for this kind of feature?

**Comment by jackpot51** [comment]
This has conflicts due that need to be resolved

**Pull request closed without merging**
