### PR TITLE
Say hi to the Red Ox, the Rust-eating mascot

### PR DESCRIPTION
**Pull request by Ticki**
**Problem**: Redox lacks of a mascot.

**Solution**: Add a mascot of course! And what would be more obvious than a red ox?

**Changes introduced by this pull request**:

- Add a raster image (png) of the new mascot.

**Drawbacks**: Lol, not other than the red ox keeps eating the man pages.

**TODOs**:
- IT SHOULD BE EVERYWHERE.
- EVERYWHERE.
- Make a oxsay:
```
/----------------\
| Install Redox. |
\----------~ ~---/
            V

           &   &
   _________&_&
 ~/  \  /  c  -\
/ |  /  \   \   \
  |    __    \__.
  |_!_|  |_!_|
```
- Find a more fancy name?
- For the sake of impersonation, get a better facial expression.
- SVGs.
- Possibly make a desktop background with it.

**Fixes**: It fixes the emptyness.

**State**: Ready, though needs certain extensions (see TODO).

**Other**: It is based on the classical symbol for the chinese "Year of the Ox".

### CODE REVIEW

**Comment by ca1ek** [comment]
It's great! I think it's too low on details, that could be improved in the future.

-----Wiadomość oryginalna-----
Od: "Ticki" <notifications@github.com>
Wysłano: ‎2016-‎03-‎28 22:07
Do: "redox-os/redox" <redox@noreply.github.com>
Temat: [redox-os/redox] Say hi to the Red Ox, the Rust-eating mascot (#595)

Problem: Redox lacks of a mascot.
Solution: Add a mascot of course! And what would be more obvious than a red ox?

Changes introduced by this pull request:
Add a raster image (png) of the new mascot. 
Drawbacks: Lol, not other than the red ox keeps eating the man pages.
TODOs:
IT SHOULD BE EVERYWHERE. 
EVERYWHERE. 
Make a oxsay: 
/----------------\
| Install Redox. |
\----------~ ~---/
            V

           &   &
   _________&_&
 ~/  \  /  c  -\
/ |  /  \   \   \
  |    __    \__.
  |_!_|  |_!_|
Find a more fancy name? 
For the sake of impersonation, get a better facial expression. 
Fixes: It fixes the emptyness.
State: Ready, though needs certain extensions (see TODO).
Other: It is based on the classical symbol for the chinese "Year of the Ox".



You can view, comment on, or merge this pull request online at:
  https://github.com/redox-os/redox/pull/595
Commit Summary
Say hi to the Red Ox, the Rust-eating mascot 
File Changes
A img/RedOx.png (0) 
Patch Links:
https://github.com/redox-os/redox/pull/595.patch 
https://github.com/redox-os/redox/pull/595.diff

**Comment by glor** [comment]
That could potentially start a shitstorm about animal rights later. Anyway - it probably would not look good, they have to many details.
SVG:
[Redox_logo.zip](https://github.com/redox-os/redox/files/198154/Redox_logo.zip)
Also there are some things I do not like about this logo.
- to little details, just the shape isn't enough
- the ox is holding it's head downwards
- the ox is standing on an unfortunate diagonal which also makes the logo look less impressive
- this way it fits neither in a round logo nor a quadratic one (very well)
I have however found a potential alternative which on the downside comes with CC BY-SA License (instead of public domain):
redox_logo2
[Redox_logo2.zip](https://github.com/redox-os/redox/files/198235/Redox_logo2.zip)
Sources:
- First logo: https://commons.wikimedia.org/wiki/File:Ox.svg
- Second logo: https://en.wikipedia.org/wiki/File:Heraldique_meubleTaureau_passant.svg

**Comment by Ticki** [comment]
> That could potentially start a shitstorm about animal rights later. 

How that?

> SVG (as i cannot upload svgs): Redox_logo.zip

I don't like that one. It is missing certain details and various subtle modification to the traditional symbol. Furthermore, the colors do not match.

> I have however found a potential alternative which on the downside comes with CC BY-SA License (instead of public domain):

To be honest, I do not like that alternative. It is too 'old-looking', whereas I'd like a more 

But I agree with your criticisms, but I think it can be fixed without a complete redesign.

**Comment by glor** [comment]
Well - it depends on what you mean with tagging an animal. if it is just an ear tag it would probably not look very well. Branding however would be a problem.

Changing the color is easy. It's just a text field in line 129   
`style="fill:#d40000"`   
I personally think the red above is to bright (mine is not bright enough). Changed it. Take whatever you favour.    
[Redox_logo.zip](https://github.com/redox-os/redox/files/198405/Redox_logo.zip)   
What other details am I missing?   

Yes it is a little old-looking. I wouldn't suggest to just replace the other logo but merely wanted a few opinions about it. Actually I think a mix of both pictures would be pretty good. A bit of the pose of my logo and the general style of yours.

**Comment by deavmi** [comment]
Install Gentoo.

**Comment by deavmi** [comment]
@ticki I like your artwork. I think the simple design is great, fits Redox OS. :+1:

**Pull request merged**
