### PR TITLE
no_alloc take Ⅲ

### PR DESCRIPTION
**Pull request by Ticki**
Now, there are three URL representations, all of which tracks both the scheme and the reference, such that reparsing is unnecessary:

1. `Url`: A struct with two string slices. It is obviously unowned, and you have to track the lifetime. You can convert a `&str` to an `Url` in `O(n)`, it simply requires finding the `:`, and taking two slices. This can be casted into the forms below by using one of the built-in methods.

2. `OwnedUrl`: This keeps two heap-allocated, owned `String`s representing the scheme and the reference. This is useful in a number of scenarios (when `Url` isn't sufficient). There is currently relatively few methods defined on it, so to manipulate it, use `as_url()`, which converts the `OwnedUrl` to an `Url`.

3. `CowUrl`: An Copy-On-Write (CoW) URL, which is useful whenever heap allocation is conditional, that is, heap allocation is only necessary in a limited number of cases.

`Url` is used for arguments. `OwnedUrl` is used for unconditional manipulation. `CowUrl` is used for conditional manipulation.

### CODE REVIEW

**Comment by Ticki** [comment]
Wow, sumodules are annoying.

**Comment by Ticki** [comment]
Damn, it does not build on the latest nightly rust:

```
libstd/src/lib.rs:178:9: 178:26 error: extern crate `core_rand` is private, and cannot be reexported (error E0364), consider declaring with `pub`, #[deny(private_in_public)] on by default
warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
```

**Comment by Ticki** [comment]
Note that this PR is not introducing errors, these errors are already in master (if you build with the latest nightly).

**Comment by jackpot51** [comment]
Thanks Ticki!

**Pull request merged**
