### PR TITLE
remove virtualbox directory if it already exists

### PR DESCRIPTION
**Pull request by esell**
A possible fix for #17 ? This assumes the VM is installed in the default virtualbox location (which maybe is a bad thing)...

### CODE REVIEW

**Comment by jackpot51** [comment]
Thanks, this looks right to me, can a Windows user confirm?

**Comment by Lacaranian** [comment]
This doesn't seem to work on Windows as it currently stands:
```
VBoxManage.exe: error: Machine settings file 'C:\Users\<insert username here>\VirtualBox VM
s\Redox\Redox.vbox' already exists
VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component M
achine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "CreateMachine(bstrSettingsFile.raw(), bstrName.
raw(), ComSafeArrayAsInParam(groups), bstrOsTypeId.raw(), createFlags.raw(), mac
hine.asOutParam())" at line 275 of file VBoxManageMisc.cpp
make: *** [virtualbox] Error 1
```

**Comment by esell** [comment]
@Lacaranian, do you have all of the output from this? Would be interesting to see what was displayed before what you previously posted. Sadly I don't have access to a WIndows box or I'd test it out locally.

**Comment by Lacaranian** [comment]
Yessir, though most of it seems to be warnings. I have MinGW (gcc version 4.9,2) with MSYS in my path, which might have caused problems between command line utility versions, but I think the Makefile does a pretty good job of only using the included windows/ exes. Here's the output from the Rust nightly 1.4 Shell:

```
C:\Users\<insert username here>\Desktop\SchemaGit\redox>windows\make virtualbox
windows/mkdir -p build
rustc --target=i686-unknown-redox-gnu.json -C no-vectorize-loops -C no-vectorize
-slp -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead-code -A depreca
ted -L build -o build/libcore.rlib rust/libcore/lib.rs
rust/libcore/lib.rs:82:12: 82:29 warning: unused or unknown feature, #[warn(unus
ed_features)] on by default
rust/libcore/lib.rs:82 #![feature(unwind_attributes)]
                                  ^~~~~~~~~~~~~~~~~
rust/libcore\panicking.rs:65:9: 65:18 warning: unused attribute, #[warn(unused_a
ttributes)] on by default
rust/libcore\panicking.rs:65         #[unwind]
                                     ^~~~~~~~~
rustc --target=i686-unknown-redox-gnu.json -C no-vectorize-loops -C no-vectorize
-slp -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead-code -A depreca
ted -L build -o build/liballoc.rlib rust/liballoc/lib.rs
rustc --target=i686-unknown-redox-gnu.json -C no-vectorize-loops -C no-vectorize
-slp -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead-code -A depreca
ted -L build -o build/liballoc_system.rlib rust/liballoc_system/lib.rs
rust/liballoc_system/lib.rs:40:52: 40:57 warning: found Rust type `usize` in for
eign module, while `libc::c_uint` or `libc::c_ulong` should be used, #[warn(impr
oper_ctypes)] on by default
rust/liballoc_system/lib.rs:40     fn memmove(dst: *mut u8, src: *const u8, size
: usize);

  ^~~~~
rust/liballoc_system/lib.rs:61:44: 61:49 warning: unused variable: `align`, #[wa
rn(unused_variables)] on by default
rust/liballoc_system/lib.rs:61 pub extern fn __rust_allocate(size: usize, align:
 usize) -> *mut u8 {
                                                                          ^~~~~
rust/liballoc_system/lib.rs:66:47: 66:55 warning: unused variable: `old_size`, #
[warn(unused_variables)] on by default
rust/liballoc_system/lib.rs:66 pub extern fn __rust_deallocate(ptr: *mut u8, old
_size: usize, align: usize) {
                                                                             ^~~
~~~~~
rust/liballoc_system/lib.rs:66:64: 66:69 warning: unused variable: `align`, #[wa
rn(unused_variables)] on by default
rust/liballoc_system/lib.rs:66 pub extern fn __rust_deallocate(ptr: *mut u8, old
_size: usize, align: usize) {

              ^~~~~
rust/liballoc_system/lib.rs:71:47: 71:55 warning: unused variable: `old_size`, #
[warn(unused_variables)] on by default
rust/liballoc_system/lib.rs:71 pub extern fn __rust_reallocate(ptr: *mut u8, old
_size: usize, size: usize,
                                                                             ^~~
~~~~~
rust/liballoc_system/lib.rs:72:33: 72:38 warning: unused variable: `align`, #[wa
rn(unused_variables)] on by default
rust/liballoc_system/lib.rs:72                                 align: usize) ->
*mut u8 {
                                                               ^~~~~
rust/liballoc_system/lib.rs:77:55: 77:63 warning: unused variable: `old_size`, #
[warn(unused_variables)] on by default
rust/liballoc_system/lib.rs:77 pub extern fn __rust_reallocate_inplace(ptr: *mut
 u8, old_size: usize,

     ^~~~~~~~
rust/liballoc_system/lib.rs:78:54: 78:59 warning: unused variable: `align`, #[wa
rn(unused_variables)] on by default
rust/liballoc_system/lib.rs:78                                         size: usi
ze, align: usize) -> usize {

    ^~~~~
rust/liballoc_system/lib.rs:83:47: 83:52 warning: unused variable: `align`, #[wa
rn(unused_variables)] on by default
rust/liballoc_system/lib.rs:83 pub extern fn __rust_usable_size(size: usize, ali
gn: usize) -> usize {
                                                                             ^~~
~~
rustc --target=i686-unknown-redox-gnu.json -C no-vectorize-loops -C no-vectorize
-slp -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead-code -A depreca
ted -L build -C lto -o build/kernel.rlib src/kernel.rs
src/kernel.rs:15:12: 15:29 warning: unused or unknown feature, #[warn(unused_fea
tures)] on by default
src/kernel.rs:15 #![feature(unwind_attributes)]
                            ^~~~~~~~~~~~~~~~~
src\audio\ac97.rs:30:24: 30:27 warning: unused variable: `buf`, #[warn(unused_va
riables)] on by default
src\audio\ac97.rs:30     fn read(&mut self, buf: &mut [u8]) -> Option<usize> {
                                            ^~~
src\audio\ac97.rs:48:17: 48:22 warning: unused variable: `po_sr`, #[warn(unused_
variables)] on by default
src\audio\ac97.rs:48             let po_sr = bus_master + 0x16;
                                     ^~~~~
src\audio\ac97.rs:49:17: 49:24 warning: unused variable: `po_picb`, #[warn(unuse
d_variables)] on by default
src\audio\ac97.rs:49             let po_picb = bus_master + 0x18;
                                     ^~~~~~~
src\audio\ac97.rs:50:17: 50:23 warning: unused variable: `po_piv`, #[warn(unused
_variables)] on by default
src\audio\ac97.rs:50             let po_piv = bus_master + 0x1A;
                                     ^~~~~~
src\audio\ac97.rs:52:17: 52:25 warning: unused variable: `glob_cnt`, #[warn(unus
ed_variables)] on by default
src\audio\ac97.rs:52             let glob_cnt = bus_master + 0x2C;
                                     ^~~~~~~~
src\audio\ac97.rs:53:17: 53:25 warning: unused variable: `glob_sta`, #[warn(unus
ed_variables)] on by default
src\audio\ac97.rs:53             let glob_sta = bus_master + 0x30;
                                     ^~~~~~~~
src\audio\ac97.rs:159:24: 159:27 warning: unused variable: `pos`, #[warn(unused_
variables)] on by default
src\audio\ac97.rs:159     fn seek(&mut self, pos: ResourceSeek) -> Option<usize>
 {
                                             ^~~
src\audio\ac97.rs:179:24: 179:27 warning: unused variable: `url`, #[warn(unused_
variables)] on by default
src\audio\ac97.rs:179     fn open(&mut self, url: &URL) -> Box<Resource> {
                                             ^~~
src\audio\intelhda.rs:54:24: 54:27 warning: unused variable: `buf`, #[warn(unuse
d_variables)] on by default
src\audio\intelhda.rs:54     fn read(&mut self, buf: &mut [u8]) -> Option<usize>
 {
                                                ^~~
src\audio\intelhda.rs:191:24: 191:27 warning: unused variable: `pos`, #[warn(unu
sed_variables)] on by default
src\audio\intelhda.rs:191     fn seek(&mut self, pos: ResourceSeek) -> Option<us
ize> {
                                                 ^~~
src\audio\intelhda.rs:212:24: 212:27 warning: unused variable: `url`, #[warn(unu
sed_variables)] on by default
src\audio\intelhda.rs:212     fn open(&mut self, url: &URL) -> Box<Resource> {
                                                 ^~~
src\audio\intelhda.rs:252:13: 252:20 warning: unused variable: `corbsts`, #[warn
(unused_variables)] on by default
src\audio\intelhda.rs:252         let corbsts = (self.base + 0x4D) as *mut u8;
                                      ^~~~~~~
src\audio\intelhda.rs:259:13: 259:20 warning: unused variable: `rirbsts`, #[warn
(unused_variables)] on by default
src\audio\intelhda.rs:259         let rirbsts = (self.base + 0x5D) as *mut u8;
                                      ^~~~~~~
src\common\resource.rs:7:5: 7:14 warning: unused import, #[warn(unused_imports)]
 on by default
src\common\resource.rs:7 use core::ptr;
                             ^~~~~~~~~
src\common\resource.rs:132:29: 132:48 warning: unreachable statement, #[warn(unr
eachable_code)] on by default
src\common\resource.rs:132                             scheme_part_i += 1;
                                                       ^~~~~~~~~~~~~~~~~~~
note: in expansion of for loop expansion
src\common\resource.rs:127:25: 133:26 note: expansion site
note: in expansion of for loop expansion
src\common\resource.rs:123:9: 138:10 note: expansion site
src\common\resource.rs:374:24: 374:27 warning: unused variable: `buf`, #[warn(un
used_variables)] on by default
src\common\resource.rs:374     fn read(&mut self, buf: &mut [u8]) -> Option<usiz
e> {
                                                  ^~~
src\common\resource.rs:378:25: 378:28 warning: unused variable: `buf`, #[warn(un
used_variables)] on by default
src\common\resource.rs:378     fn write(&mut self, buf: &[u8]) -> Option<usize>
{
                                                   ^~~
src\common\resource.rs:382:24: 382:27 warning: unused variable: `pos`, #[warn(un
used_variables)] on by default
src\common\resource.rs:382     fn seek(&mut self, pos: ResourceSeek) -> Option<u
size> {
                                                  ^~~
src\externs.rs:19:18: 19:21 warning: unused variable: `fmt`, #[warn(unused_varia
bles)] on by default
src\externs.rs:19 pub fn panic_fmt(fmt: fmt::Arguments, file: &'static str, line
: u32) -> ! {
                                   ^~~
src\graphics\bmp.rs:49:17: 49:26 warning: unused variable: `file_size`, #[warn(u
nused_variables)] on by default
src\graphics\bmp.rs:49             let file_size = getd(2);
                                       ^~~~~~~~~
src\graphics\bmp.rs:51:17: 51:28 warning: unused variable: `header_size`, #[warn
(unused_variables)] on by default
src\graphics\bmp.rs:51             let header_size = getd(0xE);
                                       ^~~~~~~~~~~
src\network\intel8254x.rs:110:24: 110:27 warning: unused variable: `url`, #[warn
(unused_variables)] on by default
src\network\intel8254x.rs:110     fn open(&mut self, url: &URL) -> Box<Resource>
 {
                                                     ^~~
src\network\rtl8139.rs:36:24: 36:27 warning: unused variable: `url`, #[warn(unus
ed_variables)] on by default
src\network\rtl8139.rs:36     fn open(&mut self, url: &URL) -> Box<Resource> {
                                                 ^~~
src\network\rtl8139.rs:226:29: 226:42 warning: value assigned to `tx_status` is
never read, #[warn(unused_assignments)] on by default
src\network\rtl8139.rs:226                         let mut tx_status = 0;
                                                       ^~~~~~~~~~~~~
note: in expansion of if let expansion
src\network\rtl8139.rs:224:17: 259:18 note: expansion site
note: in expansion of while let expansion
src\network\rtl8139.rs:223:13: 260:14 note: expansion site
src\network\scheme.rs:54:24: 54:27 warning: unused variable: `buf`, #[warn(unuse
d_variables)] on by default
src\network\scheme.rs:54     fn read(&mut self, buf: &mut [u8]) -> Option<usize>
 {
                                                ^~~
src\network\scheme.rs:90:24: 90:27 warning: unused variable: `pos`, #[warn(unuse
d_variables)] on by default
src\network\scheme.rs:90     fn seek(&mut self, pos: ResourceSeek) -> Option<usi
ze> {
                                                ^~~
src\schemes\context.rs:13:24: 13:27 warning: unused variable: `url`, #[warn(unus
ed_variables)] on by default
src\schemes\context.rs:13     fn open(&mut self, url: &URL) -> Box<Resource> {
                                                 ^~~
src\schemes\debug.rs:57:24: 57:27 warning: unused variable: `pos`, #[warn(unused
_variables)] on by default
src\schemes\debug.rs:57     fn seek(&mut self, pos: ResourceSeek) -> Option<usiz
e> {
                                               ^~~
src\schemes\debug.rs:73:24: 73:27 warning: unused variable: `url`, #[warn(unused
_variables)] on by default
src\schemes\debug.rs:73     fn open(&mut self, url: &URL) -> Box<Resource>{
                                               ^~~
src\schemes\ethernet.rs:24:24: 24:27 warning: unused variable: `buf`, #[warn(unu
sed_variables)] on by default
src\schemes\ethernet.rs:24     fn read(&mut self, buf: &mut [u8]) -> Option<usiz
e> {
                                                  ^~~
src\schemes\ethernet.rs:72:24: 72:27 warning: unused variable: `pos`, #[warn(unu
sed_variables)] on by default
src\schemes\ethernet.rs:72     fn seek(&mut self, pos: ResourceSeek) -> Option<u
size> {
                                                  ^~~
src\schemes\file.rs:174:25: 174:38 warning: unused variable: `bytes_written`, #[
warn(unused_variables)] on by default
src\schemes\file.rs:174                     let bytes_written = self.disk.write(
extent.block,
                                                ^~~~~~~~~~~~~
note: in expansion of for loop expansion
src\schemes\file.rs:168:9: 181:10 note: expansion site
src\schemes\ip.rs:26:24: 26:27 warning: unused variable: `buf`, #[warn(unused_va
riables)] on by default
src\schemes\ip.rs:26     fn read(&mut self, buf: &mut [u8]) -> Option<usize> {
                                            ^~~
src\schemes\ip.rs:92:24: 92:27 warning: unused variable: `pos`, #[warn(unused_va
riables)] on by default
src\schemes\ip.rs:92     fn seek(&mut self, pos: ResourceSeek) -> Option<usize>
{
                                            ^~~
src\schemes\memory.rs:12:24: 12:27 warning: unused variable: `url`, #[warn(unuse
d_variables)] on by default
src\schemes\memory.rs:12     fn open(&mut self, url: &URL) -> Box<Resource> {
                                                ^~~
src\schemes\random.rs:10:24: 10:27 warning: unused variable: `url`, #[warn(unuse
d_variables)] on by default
src\schemes\random.rs:10     fn open(&mut self, url: &URL) -> Box<Resource> {
                                                ^~~
src\schemes\tcp.rs:24:24: 24:27 warning: unused variable: `buf`, #[warn(unused_v
ariables)] on by default
src\schemes\tcp.rs:24     fn read(&mut self, buf: &mut [u8]) -> Option<usize> {
                                             ^~~
src\schemes\tcp.rs:140:24: 140:27 warning: unused variable: `pos`, #[warn(unused
_variables)] on by default
src\schemes\tcp.rs:140     fn seek(&mut self, pos: ResourceSeek) -> Option<usize
> {
                                              ^~~
src\schemes\tcp.rs:243:40: 243:43 warning: unused variable: `syn`, #[warn(unused
_variables)] on by default
src\schemes\tcp.rs:243     pub fn server_establish(&mut self, syn: TCP) -> bool
{
                                                              ^~~
src\schemes\time.rs:12:24: 12:27 warning: unused variable: `url`, #[warn(unused_
variables)] on by default
src\schemes\time.rs:12     fn open(&mut self, url: &URL) -> Box<Resource> {
                                              ^~~
src\schemes\udp.rs:25:24: 25:27 warning: unused variable: `buf`, #[warn(unused_v
ariables)] on by default
src\schemes\udp.rs:25     fn read(&mut self, buf: &mut [u8]) -> Option<usize> {
                                             ^~~
src\schemes\udp.rs:88:24: 88:27 warning: unused variable: `pos`, #[warn(unused_v
ariables)] on by default
src\schemes\udp.rs:88     fn seek(&mut self, pos: ResourceSeek) -> Option<usize>
 {
                                             ^~~
src\syscall\handle.rs:70:27: 70:33 warning: unused variable: `status`, #[warn(un
used_variables)] on by default
src\syscall\handle.rs:70 pub unsafe fn do_sys_exit(status: isize) {
                                                   ^~~~~~
src\syscall\handle.rs:128:44: 128:49 warning: unused variable: `flags`, #[warn(u
nused_variables)] on by default
src\syscall\handle.rs:128 pub unsafe fn do_sys_open(path: *const u8, flags: isiz
e, mode: isize) -> usize {
                                                                     ^~~~~
src\syscall\handle.rs:128:58: 128:62 warning: unused variable: `mode`, #[warn(un
used_variables)] on by default
src\syscall\handle.rs:128 pub unsafe fn do_sys_open(path: *const u8, flags: isiz
e, mode: isize) -> usize {

   ^~~~
src\syscall\handle.rs:212:25: 212:36 warning: variable does not need to be mutab
le, #[warn(unused_mut)] on by default
src\syscall\handle.rs:212     if let Option::Some(mut current) = contexts.get(co
ntext_i) {
                                                  ^~~~~~~~~~~
note: in expansion of if let expansion
src\syscall\handle.rs:212:5: 228:6 note: expansion site
src\usb\ehci.rs:146:13: 146:20 warning: unused variable: `FRINDEX`, #[warn(unuse
d_variables)] on by default
src\usb\ehci.rs:146         let FRINDEX = (opbase + 0xC) as *mut u32;
                                ^~~~~~~
src\usb\ehci.rs:147:13: 147:26 warning: unused variable: `CTRLDSSEGMENT`, #[warn
(unused_variables)] on by default
src\usb\ehci.rs:147         let CTRLDSSEGMENT = (opbase + 0x10) as *mut u32;
                                ^~~~~~~~~~~~~
src\usb\ehci.rs:148:13: 148:29 warning: unused variable: `PERIODICLISTBASE`, #[w
arn(unused_variables)] on by default
src\usb\ehci.rs:148         let PERIODICLISTBASE = (opbase + 0x14) as *mut u32;
                                ^~~~~~~~~~~~~~~~
src\usb\ehci.rs:149:13: 149:26 warning: unused variable: `ASYNCLISTADDR`, #[warn
(unused_variables)] on by default
src\usb\ehci.rs:149         let ASYNCLISTADDR = (opbase + 0x18) as *mut u32;
                                ^~~~~~~~~~~~~
src\usb\uhci.rs:307:13: 307:19 warning: unused variable: `usbcmd`, #[warn(unused
_variables)] on by default
src\usb\uhci.rs:307         let usbcmd = base;
                                ^~~~~~
src\usb\uhci.rs:308:13: 308:19 warning: unused variable: `usbsts`, #[warn(unused
_variables)] on by default
src\usb\uhci.rs:308         let usbsts = base + 2;
                                ^~~~~~
src\usb\uhci.rs:309:13: 309:20 warning: unused variable: `usbintr`, #[warn(unuse
d_variables)] on by default
src\usb\uhci.rs:309         let usbintr = base + 4;
                                ^~~~~~~
src\usb\uhci.rs:382:13: 382:19 warning: unused variable: `usbcmd`, #[warn(unused
_variables)] on by default
src\usb\uhci.rs:382         let usbcmd = base;
                                ^~~~~~
src\usb\uhci.rs:511:29: 511:35 warning: unused variable: `usbcmd`, #[warn(unused
_variables)] on by default
src\usb\uhci.rs:511                         let usbcmd = base;
                                                ^~~~~~
note: in expansion of for loop expansion
src\usb\uhci.rs:483:9: 588:10 note: expansion site
src\usb\uhci.rs:569:29: 569:53 warning: unreachable statement, #[warn(unreachabl
e_code)] on by default
src\usb\uhci.rs:569                             unalloc(in_td as usize);
                                                ^~~~~~~~~~~~~~~~~~~~~~~~
note: in expansion of for loop expansion
src\usb\uhci.rs:483:9: 588:10 note: expansion site
src\usb\uhci.rs:605:13: 605:19 warning: unused variable: `sofmod`, #[warn(unused
_variables)] on by default
src\usb\uhci.rs:605         let sofmod = base + 0xC;
                                ^~~~~~
windows/i386-elf-ld -m elf_i386 -o filesystem/kernel.bin -T src/kernel.ld build/
kernel.rlib
rustc --target=i686-unknown-redox-gnu.json -C no-vectorize-loops -C no-vectorize
-slp -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead-code -A depreca
ted -L build -o build/libredox.rlib libredox/lib.rs
libredox\../src/externs.rs:19:18: 19:21 warning: unused variable: `fmt`, #[warn(
unused_variables)] on by default
libredox\../src/externs.rs:19 pub fn panic_fmt(fmt: fmt::Arguments, file: &'stat
ic str, line: u32) -> ! {
                                               ^~~
libredox\../src/graphics\bmp.rs:49:17: 49:26 warning: unused variable: `file_siz
e`, #[warn(unused_variables)] on by default
libredox\../src/graphics\bmp.rs:49             let file_size = getd(2);
                                                   ^~~~~~~~~
libredox\../src/graphics\bmp.rs:51:17: 51:28 warning: unused variable: `header_s
ize`, #[warn(unused_variables)] on by default
libredox\../src/graphics\bmp.rs:51             let header_size = getd(0xE);
                                                   ^~~~~~~~~~~
windows/sed "s|APPLICATION_PATH|../filesystem/apps/echo/echo.rs|" src/program.rs
 > build/`windows/basename apps/echo/echo`.gen
rustc --target=i686-unknown-redox-gnu.json -C no-vectorize-loops -C no-vectorize
-slp -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead-code -A depreca
ted -L build -C lto -o build/`windows/basename apps/echo/echo`.rlib build/`windo
ws/basename apps/echo/echo`.gen
windows/i386-elf-ld -m elf_i386 -o filesystem/apps/echo/echo.bin -T src/program.
ld build/`windows/basename apps/echo/echo`.rlib
windows/sed "s|APPLICATION_PATH|../filesystem/apps/editor/editor.rs|" src/progra
m.rs > build/`windows/basename apps/editor/editor`.gen
rustc --target=i686-unknown-redox-gnu.json -C no-vectorize-loops -C no-vectorize
-slp -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead-code -A depreca
ted -L build -C lto -o build/`windows/basename apps/editor/editor`.rlib build/`w
indows/basename apps/editor/editor`.gen
windows/i386-elf-ld -m elf_i386 -o filesystem/apps/editor/editor.bin -T src/prog
ram.ld build/`windows/basename apps/editor/editor`.rlib
windows/sed "s|APPLICATION_PATH|../filesystem/apps/file_manager/file_manager.rs|
" src/program.rs > build/`windows/basename apps/file_manager/file_manager`.gen
rustc --target=i686-unknown-redox-gnu.json -C no-vectorize-loops -C no-vectorize
-slp -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead-code -A depreca
ted -L build -C lto -o build/`windows/basename apps/file_manager/file_manager`.r
lib build/`windows/basename apps/file_manager/file_manager`.gen
windows/i386-elf-ld -m elf_i386 -o filesystem/apps/file_manager/file_manager.bin
 -T src/program.ld build/`windows/basename apps/file_manager/file_manager`.rlib
windows/sed "s|APPLICATION_PATH|../filesystem/apps/httpd/httpd.rs|" src/program.
rs > build/`windows/basename apps/httpd/httpd`.gen
rustc --target=i686-unknown-redox-gnu.json -C no-vectorize-loops -C no-vectorize
-slp -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead-code -A depreca
ted -L build -C lto -o build/`windows/basename apps/httpd/httpd`.rlib build/`win
dows/basename apps/httpd/httpd`.gen
<redox macros>:2:1: 2:63 warning: unreachable statement, #[warn(unreachable_code
)] on by default
<redox macros>:2 { print ! ( $ text ) ; print ! ( & "\n" . to_string (  ) ) ; }
) ;
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<redox macros>:1:1: 2:67 note: in expansion of println!
build\../filesystem/apps/httpd/httpd.rs:160:5: 160:48 note: expansion site
windows/i386-elf-ld -m elf_i386 -o filesystem/apps/httpd/httpd.bin -T src/progra
m.ld build/`windows/basename apps/httpd/httpd`.rlib
windows/sed "s|APPLICATION_PATH|../filesystem/apps/game/game.rs|" src/program.rs
 > build/`windows/basename apps/game/game`.gen
rustc --target=i686-unknown-redox-gnu.json -C no-vectorize-loops -C no-vectorize
-slp -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead-code -A depreca
ted -L build -C lto -o build/`windows/basename apps/game/game`.rlib build/`windo
ws/basename apps/game/game`.gen
windows/i386-elf-ld -m elf_i386 -o filesystem/apps/game/game.bin -T src/program.
ld build/`windows/basename apps/game/game`.rlib
windows/sed "s|APPLICATION_PATH|../filesystem/apps/player/player.rs|" src/progra
m.rs > build/`windows/basename apps/player/player`.gen
rustc --target=i686-unknown-redox-gnu.json -C no-vectorize-loops -C no-vectorize
-slp -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead-code -A depreca
ted -L build -C lto -o build/`windows/basename apps/player/player`.rlib build/`w
indows/basename apps/player/player`.gen
windows/i386-elf-ld -m elf_i386 -o filesystem/apps/player/player.bin -T src/prog
ram.ld build/`windows/basename apps/player/player`.rlib
windows/sed "s|APPLICATION_PATH|../filesystem/apps/terminal/terminal.rs|" src/pr
ogram.rs > build/`windows/basename apps/terminal/terminal`.gen
rustc --target=i686-unknown-redox-gnu.json -C no-vectorize-loops -C no-vectorize
-slp -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead-code -A depreca
ted -L build -C lto -o build/`windows/basename apps/terminal/terminal`.rlib buil
d/`windows/basename apps/terminal/terminal`.gen
build\../filesystem/apps/terminal/terminal.rs:28:24: 28:28 warning: unused varia
ble: `args`, #[warn(unused_variables)] on by default
build\../filesystem/apps/terminal/terminal.rs:28             main: box |args: &V
ec<String>|{
                                                                        ^~~~
build\../filesystem/apps/terminal/terminal.rs:124:34: 124:38 warning: unused var
iable: `size`, #[warn(unused_variables)] on by default
build\../filesystem/apps/terminal/terminal.rs:124                     Option::So
me(size) => println!(String::from_utf8(&vec)),

   ^~~~
windows/i386-elf-ld -m elf_i386 -o filesystem/apps/terminal/terminal.bin -T src/
program.ld build/`windows/basename apps/terminal/terminal`.rlib
windows/sed "s|APPLICATION_PATH|../filesystem/apps/viewer/viewer.rs|" src/progra
m.rs > build/`windows/basename apps/viewer/viewer`.gen
rustc --target=i686-unknown-redox-gnu.json -C no-vectorize-loops -C no-vectorize
-slp -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead-code -A depreca
ted -L build -C lto -o build/`windows/basename apps/viewer/viewer`.rlib build/`w
indows/basename apps/viewer/viewer`.gen
windows/i386-elf-ld -m elf_i386 -o filesystem/apps/viewer/viewer.bin -T src/prog
ram.ld build/`windows/basename apps/viewer/viewer`.rlib
windows/mkdir -p build
windows/nasm -f elf -o build/`windows/basename apps/bad_code/bad_code.o` filesys
tem/apps/bad_code/bad_code.asm
windows/i386-elf-ld -m elf_i386 -o filesystem/apps/bad_code/bad_code.bin -T src/
program.ld build/`windows/basename apps/bad_code/bad_code`.o
windows/mkdir -p build
windows/nasm -f elf -o build/`windows/basename apps/bad_data/bad_data.o` filesys
tem/apps/bad_data/bad_data.asm
windows/i386-elf-ld -m elf_i386 -o filesystem/apps/bad_data/bad_data.bin -T src/
program.ld build/`windows/basename apps/bad_data/bad_data`.o
windows/mkdir -p build
windows/nasm -f elf -o build/`windows/basename apps/bad_segment/bad_segment.o` f
ilesystem/apps/bad_segment/bad_segment.asm
windows/i386-elf-ld -m elf_i386 -o filesystem/apps/bad_segment/bad_segment.bin -
T src/program.ld build/`windows/basename apps/bad_segment/bad_segment`.o
windows/mkdir -p build
windows/nasm -f elf -o build/`windows/basename apps/linux_stdio/linux_stdio.o` f
ilesystem/apps/linux_stdio/linux_stdio.asm
windows/i386-elf-ld -m elf_i386 -o filesystem/apps/linux_stdio/linux_stdio.bin -
T src/program.ld build/`windows/basename apps/linux_stdio/linux_stdio`.o
windows/find filesystem -not -path '*/\.*' -type f -o -type l | windows/cut -d '
/' -f2- | windows/sort | windows/awk '{printf("file %d,\"%s\"\n", NR, $0)}' > bu
ild/filesystem.gen
windows/nasm -f bin -o build/harddrive.bin -ibuild/ -isrc/ -ifilesystem/ src/loa
der.asm
echo "Delete VM"
Delete VM
"C:/Program Files/Oracle/VirtualBox/VBoxManage" unregistervm Redox --delete; \
        if [ $? -ne 0 ]; \
        then \
                if [ -d "$HOME/VirtualBox VMs/Redox" ]; \
                then \
                        echo "redox directory exists, deleting..."; \
                        windows/rm -rf "$HOME/VirtualBox VMs/Redox"; \
                fi \
        fi
VBoxManage.exe: error: Could not find a registered machine named 'Redox'
VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), compo
nent VirtualBox, interface IVirtualBox, callee IUnknown
VBoxManage.exe: error: Context: "FindMachine(Bstr(VMName).raw(), machine.asOutPa
ram())" at line 154 of file VBoxManageMisc.cpp
echo "Delete Disk"
Delete Disk
windows/rm harddrive.vdi
windows/rm: cannot lstat `harddrive.vdi': No such file or directory
make: [virtualbox] Error 1 (ignored)
echo "Create VM"
Create VM
"C:/Program Files/Oracle/VirtualBox/VBoxManage" createvm --name Redox --register

VBoxManage.exe: error: Machine settings file 'C:\Users\<insert username here>\VirtualBox VM
s\Redox\Redox.vbox' already exists
VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component M
achine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "CreateMachine(bstrSettingsFile.raw(), bstrName.
raw(), ComSafeArrayAsInParam(groups), bstrOsTypeId.raw(), createFlags.raw(), mac
hine.asOutParam())" at line 275 of file VBoxManageMisc.cpp
make: *** [virtualbox] Error 1

C:\Users\<insert username here>\Desktop\SchemaGit\redox>
```

**Comment by jackpot51** [comment]
Hey Lac, can you take a look at #42 
I can't boot into Windows right now, and need information about whether USERPROFILE is a good variable

**Pull request merged**
