### PR TITLE
[WIP] Implementation of capabilities.

### PR DESCRIPTION
**Pull request by Yoric**
Opening this branch to encourage feedback & reviews.

### CODE REVIEW

**Comment by Yoric** [comment]
@ticki, if you wish to take a look, this is what I've come up with so far.

**Comment by ticki** [comment]
Looks very cool!

**Comment by Yoric** [comment]
@ticki Updated with actual details on the syscalls.

**Comment by Yoric** [comment]
I have rebooted this from https://github.com/redox-os/rfcs/pull/2.

**Pull request closed without merging**
