### PR TITLE
Implement Metric<T> enum for matching file sizes

### PR DESCRIPTION
**Pull request by stratact**
Because it's Rustic and cooler this way :sunglasses:

### CODE REVIEW

**Comment by Lacaranian** [comment]
Since we're still using the if/else construct, we're only adding more code to do the same thing. Making this better might take more language features.

**Comment by stratact** [comment]
Closing. Will come back to this in a new PR if we can find a way to not use the if/else construct and if necessary.

**Comment by NobbZ** [comment]
I have some solution in my mind, I hope I will find some spare time...

stratact <notifications@github.com> schrieb am Mi., 21. Okt. 2015 19:18:

**Comment by stratact** [comment]
@NobbZ cool and take your time.

**Pull request closed without merging**
