### PR TITLE
Disable seccomp and apparmor to compile Redox with Docker image.

### PR DESCRIPTION
**Pull request by mssun**
Problem:
Won't compile on machine with apparmor enabled.

Solution:
Disable seccomp and apparmor.

Changes introduced by this pull request:

  - docker/README.md

### CODE REVIEW

**Comment by ids1024** [comment]
Do you know why this was causing an issue?

**Comment by mssun** [comment]
Because with apparmor enabled, the fuse related command such as `mount` will not work in the docker with "permission denied" error.

```
cargo run --manifest-path redoxfs/Cargo.toml --quiet --release --bin redoxfs -- build/filesystem.bin.partial build/filesystem/
redoxfs: opened filesystem build/filesystem.bin.partial
fuse: mount failed: Permission denied
thread 'main' panicked at 'Unable to mount filesystem. Error Permission denied (os error 13)', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/fuse-0.2.8/src/session.rs:52:24
note: Run with `RUST_BACKTRACE=1` for a backtrace.
sleep 2
pgrep redoxfs
make: *** [build/filesystem.bin] Error 1
mk/filesystem.mk:2: recipe for target 'build/filesystem.bin' failed
```

References:
  - https://docs.docker.com/engine/security/apparmor/
  - https://docs.docker.com/engine/security/seccomp/

I update the commit. Sorry for the typo. Please squash them into one commit if possible. Thank you.

**Comment by fengalin** [comment]
Could you please add it as a separate alternative? The section you modified targets `selinux` systems. The command you propose produces a `permission denied` on Fedora 26.

**Comment by mssun** [comment]
@fengalin Thanks for pointing out this issue. I rephrase the sentences and separate settings of SELinux, seccomp and AppArmor enabled systems.

**Comment by fengalin** [comment]
Thank you!

**Comment by fengalin** [comment]
@jackpot51 @batonius : looks good to me, what do you think?

**Comment by mssun** [comment]
Any updates? Feel free to let me know if there are any problems.

**Comment by jackpot51** [comment]
Looks good!

**Pull request merged**
