### PR TITLE
Add debug! and debugln! macros for debug syscalls (to print to system console)

### PR DESCRIPTION
**Pull request by Ticki**
I thought this was needed for debugging.

### CODE REVIEW

**Comment by jackpot51** [comment]
Thanks, really needed these!

**Comment by stratact** [comment]
Nice work!

**Comment by jackpot51** [comment]
Can you add these to the kernel as well?

do_sys_debug is the kernel equivalent to sys_debug

**Comment by Ticki** [comment]
Will do.

**Pull request merged**
