### PR TITLE
Avoid dynamic dispatch, allocations, clones, and other expensive operations on common objects and structures in the kernel (Scheme, KScheme, URL, Resource, etc.)

### PR DESCRIPTION
**Pull request by Ticki**
WIP. Do not merge.

There are still some bugs (and errors?). If anyone wants to play around with it, feel free to do so.

### CODE REVIEW

**Comment by Ticki** [comment]
So .. many .. allocations. I'm tired now. Good night.

**Comment by jackpot51** [comment]
Merged this into no_kernel_alloc branch

**Comment by jackpot51** [comment]
Working on making it run correctly now

**Comment by jackpot51** [comment]
A warning: Some things must, must, must be allocated. If I find things like this I will make a note of them here

**Comment by jackpot51** [comment]
Honestly, I prefer to do this a different way

**Comment by Ticki** [comment]
@jackpot51 Could you expand on what you think is wrong?

**Comment by jackpot51** [comment]
I believe it to be impossible to have context have a lifetime, I believe it must be fully owned. We can certainly replace Url with &str up to that point, but it must be allocated to pass context memory boundaries, like in the execute function.

**Comment by Ticki** [comment]
@jackpot51 I get your point. I'll remove the context lifetime.

**Comment by Ticki** [comment]
@jackpot51 I updated it know, however it is still incomplete. When I get time, later, I'll try to fix it.

**Comment by jackpot51** [comment]
That's good. The name can't be static str because it comes from a non-static argument provided in the execve syscall.

**Comment by jackpot51** [comment]
This is still available in the kernel_no_alloc branch. I am closing because I am working out a way to minimize kernel allocations along with page table fixes in another branch

**Comment by Ticki** [comment]
Sure.

**Pull request closed without merging**
