### PR TITLE
Generation of documentation for the new libraries

### PR DESCRIPTION
**Pull request by Ticki**
**Problem**: The generation of documentation for the new programs and libraries is not automated.

**Solution**: Add it to `make doc` effectively making the documentation for the new crates be generated and uploaded to redox-os.org.

**Changes introduced by this pull request**:

- Add `libmalloc` submodule.
- Add doc-gen for `libextra`.
- Add doc-gen for `libmalloc`.
- Add doc-gen for `binutils`.
- Add doc-gen for `zfs`.
- Add doc-gen for `sodium`.

**Drawbacks**: Possibly slower doc generation.

**TODOs**:

- Add links to the website.
- Make private items appear too in the documentation.
- Add doc generation for the rest of the crates.

**State**: Ready.

**Blocking/related**: Part of the documentation effort, #525.

### CODE REVIEW

**Comment by jackpot51** [comment]
The doc gen is configured to show private docs

**Comment by jackpot51** [comment]
See the RUSTDOC variable

**Comment by Ticki** [comment]
Oh, neat. Also, how and when do it build?

**Comment by jackpot51** [comment]
When the redox repo changes, it is built by jenkins

**Pull request merged**
