### PR TITLE
Module name prefixing and Glob Cleanup

### PR DESCRIPTION
**Pull request by stratact**
~~Work-in-progress. Don't merge yet.~~

### CODE REVIEW

**Comment by stratact** [comment]
@jackpot51 I decided to import just the types from `drivers::{pio, pciconfig}` directly, instead of prefixing the module name. The functions, I prefix only.

**Comment by jackpot51** [comment]
That looks good to me.

**Comment by stratact** [comment]
@jackpot51 I got a couple of questions, could you come on IRC?

**Comment by jackpot51** [comment]
Hey Stratact, I was asleep, do you still have questions?

**Comment by stratact** [comment]
@jackpot51, hmm the embedded message in the code didn't show it count. Did you get the ping?

**Comment by jackpot51** [comment]
The programs::common stuff was stupid, I did a lot of pub uses there for laziness's sake. Any that you remove would be awesome.

**Comment by stratact** [comment]
Will do, thanks. :smile:

**Comment by stratact** [comment]
My head is ready to explode from all of this re-routing of imports. :weary:

I took care of the `common::programs` modules but there is still plenty of globs to remove from other modules...

**Comment by stratact** [comment]
@jackpot51 how does it look so far?

**Comment by jackpot51** [comment]
I really appreciate this, I know my old code is pretty ugly :-/. It looks good!

**Comment by stratact** [comment]
I think this is good enough for now. I think it would be good to get all of these changes before other big changes get merged in.

I was looking at `common::paging` and I was getting some different ideas of organizing it, which I would like to chat with you about.

**Comment by jackpot51** [comment]
I am running errands, will be on IRC shortly. Also working on slack if interested

**Pull request merged**
