### PR TITLE
add dependencies for building and running redox on SUSE

### PR DESCRIPTION
**Pull request by MaximilianMeister**

### CODE REVIEW

**Comment by Ticki** [comment]
:+1:

**Comment by MaximilianMeister** [comment]
```
- Starting Orbital
    Console: Press F1
    Desktop: Press F2
INIT: Executing file:/apps/login/main.bin
PID 12: file:/apps/login/main.bin
  INT E: Page fault
    CS:  0000001B    IP:  00000023    FLG: 00010283
    SS:  00000000    SP:  700FED74    BP:  700FEE00
    AX:  080527E0    BX:  08053000    CX:  700FEE38    DX:  08052888
    DI:  700FEE20    SI:  700FEE20
    CR0: 80000013    CR2: 00000023    CR3: 00200000    CR4: 00000600
    ERR: 00000004

```
The desktop starts fine, but doesn't allow much interaction yet...

@Ticki 
somehow the console is not working properly yet. maybe you have an idea what I could be missing?

**Comment by Ticki** [comment]
There's currently some issues when using VirtualBox. Try Qemu instead. See https://github.com/redox-os/redox/issues/345.

**Comment by MaximilianMeister** [comment]
@Ticki hmm... I have used Qemu, I haven't even tried Virtualbox

**Comment by polymetric1** [comment]
My Qemu won't start without KVM, and I can't get virtualbox to work at all (has nothing to do with Redox). Maybe try Qemu with no KVM, then try VB.

**Pull request merged**
