### PR TITLE
update travisci to build on osx

### PR DESCRIPTION
**Pull request by esell**
Adds osx back in to travis-ci builds.

### CODE REVIEW

**Comment by esell** [comment]
Just a note that the osx build took about 18 minutes because of all the homebrew crap :(

**Comment by esell** [comment]
I took out the gcc stuff, seems to work locally but the travis-ci stopped halfway through for some reason...

**Comment by stratact** [comment]
@esell something about brew not linking

https://travis-ci.org/redox-os/redox/jobs/83516356#L2170

**Comment by stratact** [comment]
Nice work!

**Comment by esell** [comment]
ugh, missed a step, looks like it's good to go now!

**Comment by hauleth** [comment]
ryan_reynolds_but_why

**Comment by esell** [comment]
After deciphering your gif @hauleth I'm assuming you are asking why test the build on osx? I guess my thinking was since there are instructions in the readme on how to build on osx, we should probably make sure the build works.

For me it is quite frustrating to download a project and follow the documented steps to build it only to find out it doesn't work. You then spend 30 minutes trying to get the build working instead of playing around with/hacking on the project you just downloaded.

**Comment by jackpot51** [comment]
Good job! I think we should test on OSX too

**Pull request merged**
