### PR TITLE
Update README.md build instructions to work with Makefile changes

### PR DESCRIPTION
**Pull request by polymetric1**

### CODE REVIEW

**Comment by polymetric1** [comment]
For some reason this backrevs crates/ion, hold the PR until I figure out why it did that and fix it

**Comment by Ticki** [comment]
I'll just update it.

**Comment by polymetric1** [comment]
What do you mean? (I know absolutely nothing about submodules)

**Comment by Ticki** [comment]
Go into the folders that needs update, and pull the latest upstream.

**Comment by polymetric1** [comment]
Oh, ok. thanks

**Comment by Ticki** [comment]
np

**Pull request merged**
