### PR TITLE
x86_64 paging init clears too much memory

### PR DESCRIPTION
**Pull request by Roxxik**

### CODE REVIEW

**Comment by jackpot51** [comment]
The tables are 4096 bytes each, so this was correct.

**Comment by jackpot51** [comment]
If you change it to 3 * 4096 / 8 and then use stosq I will merge

**Comment by Roxxik** [comment]
uh you're right :O I totally mixed it up.

**Comment by Roxxik** [comment]
The github intern Editor mixed something up, the comment looks wrong

**Comment by Roxxik** [comment]
i clicked at `4 Bytes`, but it changed `PD` :/

**Comment by jackpot51** [comment]
does it look ok now: https://github.com/redox-os/redox/blob/master/kernel/asm/startup-x86_64.asm

**Comment by Roxxik** [comment]
yup

**Comment by Roxxik** [comment]
-.- I just saw, that i've only tested the i386 version.

I now why I put there a stosd, this is still real mode, and stosq is not supported there.

**Comment by Roxxik** [comment]
And I just realized, that x86_64 doesn't boot at all for me, even when using a version from yesterday

**Comment by jackpot51** [comment]
It doesn't boot yet, not sure why

**Comment by Roxxik** [comment]
Page Fault

**Comment by Roxxik** [comment]
00018883132i[CPU0  ] CPU is in long mode (active)
00018883132i[CPU0  ] CS.mode = 64 bit
00018883132i[CPU0  ] SS.mode = 64 bit
00018883132i[CPU0  ] EFER   = 0x00000500
00018883132i[CPU0  ] | RAX=0000000000000010  RBX=00000000e0000013
00018883132i[CPU0  ] | RCX=0000000000001640  RDX=0000000000000000
00018883132i[CPU0  ] | RSP=00000000001fff80  RBP=0000000000000000
00018883132i[CPU0  ] | RSI=000000000008c000  RDI=0000000000081000
00018883132i[CPU0  ] |  R8=0000000000000000   R9=0000000000000000
00018883132i[CPU0  ] | R10=0000000000000000  R11=0000000000000000
00018883132i[CPU0  ] | R12=0000000000000000  R13=0000000000000000
00018883132i[CPU0  ] | R14=0000000000000000  R15=0000000000000000
00018883132i[CPU0  ] | IOPL=0 id vip vif ac vm RF nt of df if tf sf zf af PF cf
00018883132i[CPU0  ] | SEG sltr(index|ti|rpl)     base    limit G D
00018883132i[CPU0  ] |  CS:0008( 0001| 0|  0) 00000000 ffffffff 1 0
00018883132i[CPU0  ] |  DS:0010( 0002| 0|  0) 00000000 ffffffff 1 0
00018883132i[CPU0  ] |  SS:0010( 0002| 0|  0) 00000000 ffffffff 1 0
00018883132i[CPU0  ] |  ES:0010( 0002| 0|  0) 00000000 ffffffff 1 0
00018883132i[CPU0  ] |  FS:0010( 0002| 0|  0) 00000000 ffffffff 1 0
00018883132i[CPU0  ] |  GS:0010( 0002| 0|  0) 00000000 ffffffff 1 0
00018883132i[CPU0  ] |  MSR_FS_BASE:0000000000000000
00018883132i[CPU0  ] |  MSR_GS_BASE:0000000000000000
00018883132i[CPU0  ] | RIP=000000000000840c (000000000000840c)
00018883132i[CPU0  ] | CR0=0xe0000013 CR2=0x00000000000092fa
00018883132i[CPU0  ] | CR3=0x00080000 CR4=0x00000630
00018883132e[CPU0  ] exception(): 3rd (14) exception with no resolution, shutdown status is 00h, resetting

**Comment by Roxxik** [comment]
exception 14 is a page fault, and this happens in startup-x84_64.asm line 97 `rep movsq` this is the instruction, that relocates the kernel. This instruction touches memory in rdi and rsi, which are 0x8C000 and 0x81000

**Comment by Roxxik** [comment]
And we're getting a triple fault, because of a faulty IDT

**Comment by Roxxik** [comment]
still stosq in real mode makes no sense, i'll send a pull request to fix that

**Comment by jackpot51** [comment]
oh right

**Pull request merged**
