### PR TITLE
Big IO change!

### PR DESCRIPTION
**Pull request by Ticki**
Changes include:

1. Almost 100% libstd compatibility.
2. Added BufRead and BufWrite.
3. Rewrote the IO error handling to match the upstream one.
4. Buffered streams.
5. Flushing.
6. `Sink`
7. `Cursor`
8. `Tee`
9. Buffered `Bytes` iterator.

and much more.

This makes libredox::io almost identical to std::io. Pretty much all of the doc comments are stolen from libstd's, the same is true for some of the code.

Let me know if you find any bugs.

### CODE REVIEW

**Comment by jackpot51** [comment]
Awesome! there is a merge error in io/mod.rs

**Comment by Ticki** [comment]
Dammit.

**Comment by Ticki** [comment]
Fixed.

**Comment by stratact** [comment]
Nice work! :+1:

**Pull request merged**
