### PR TITLE
[Kernel] Improve pseudo random generator and memory management

### PR DESCRIPTION
**Pull request by Ticki**

### CODE REVIEW

**Comment by jackpot51** [comment]
You cannot remove those memsets!!!!!!!!

If an application frees a password string, another allocs it, it could read the data. Allocated pages are always set to 0 in other operating systems!

**Comment by Ticki** [comment]
Malloc and calloc are different in many OSes.

**Comment by jackpot51** [comment]
Those are implemmented in userspace!!! The kernel call is brk, look it up and undo your removal of the memsets ASAP

**Comment by Ticki** [comment]
I see.

**Comment by Ticki** [comment]
lt's fixed now.

**Comment by Ticki** [comment]
For the record I'm working on buddy memory management in the kernel (to reduce external fragmentation).

**Pull request merged**
