### PR TITLE
Bootstrap fuse dependency & more

### PR DESCRIPTION
**Pull request by DomThePorcupine**
**Problem**: Building Redox now depends on fuse

**Solution**: Add fuse to list of dependencies installed by the package managers

**Changes introduced by this pull request**:
- Add fuse to dependencies
- Clean up cloning, and rust install
- Added a function to report whether the last travis build was successful
- Changed rust install to multirust

It would be greatly appreciated if people could test it out on the various operating systems
to confirm that I got all the package names correct. Right now OSX and Arch are working 

`curl -sf https://raw.githubusercontent.com/DomThePorcupine/redox/master/bootstrap.sh -o bootstrap.sh && bash -e bootstrap.sh`
- [x] OSX
- [x] Arch Linux
- [x] Debian & derivatives
- [ ] Suse & derivatives
- [x] Fedora
- [x] Gentoo

------

### CODE REVIEW

**Comment by jackpot51** [comment]
What is the best way to test on a system that has already run this?

**Comment by DomThePorcupine** [comment]
@jackpot51 Honestly, I am really not sure other than just running it in a temp directory and commenting out gitClone in the endMessage function

**Comment by jackpot51** [comment]
I can bring up a couple VMs for the other systems

**Comment by jackpot51** [comment]
On debian, wget is available by default, not curl

Just a note

**Comment by jackpot51** [comment]
## Testing on Fedora

TODO

**Comment by jackpot51** [comment]
## Testing on Arch

Works

**Comment by jackpot51** [comment]
## Testing on openSUSE

TODO

**Comment by jackpot51** [comment]
## Testing on Ubuntu

Newest change works

**Comment by DomThePorcupine** [comment]
Shoutout to @dalance, could you test gentoo? I think you were the one that put it in.

**Comment by dalance** [comment]
I'd tested on Gentoo, and it works fine.

**Comment by jackpot51** [comment]
Not sure about suse, I will merge

**Pull request merged**
