### PR TITLE
Arch Linux Setup Script

### PR DESCRIPTION
**Pull request by mgattozzi**
The setup script allows Arch Linux users to be setup and contribute to the repository or run Redox. The Readme file has also been updated to show those users how to setup and run Redox.

### CODE REVIEW

**Comment by jackpot51** [comment]
Awesome, thanks!

**Comment by mgattozzi** [comment]
You're welcome!

**Comment by jackpot51** [comment]
Hey @mgattozzi, are you on slack yet?

**Comment by mgattozzi** [comment]
I am now!

**Pull request merged**
