### PR TITLE
OptionSlice redux (yes, I spelled the 2nd word correctly :P)

### PR DESCRIPTION
**Pull request by stratact**
For the same reasons in PR #474 and after much thought, I was able to make `.option_slice()` take a range much like `get_slice()` except it takes `Option<usize>` for both start and end of the range: So here are the following changes:

* Adds `OptionSlice` which takes `Option<usize>` as **range** parameters
* Moves both `GetSlice` and `OptionSlice` to a `slice` module
* Use `OptionSlice` in the more appropriate places where `GetSlice` is not well suited
* Cleanup unused imports in `GetSlice`

### CODE REVIEW

**Comment by jackpot51** [comment]
Cool, I like having both so you can pass find straight to get_slice

**Comment by stratact** [comment]
Alright, will attempt that at the next PR.

**Comment by jackpot51** [comment]
Is it possible?

**Comment by jackpot51** [comment]
To combine both into one?

**Comment by stratact** [comment]
@LazyOxen actually attempt at it in an spoof version and I cleaned it up afterwords. I think I would be able to adapt it for `GetSlice`.

**Comment by jackpot51** [comment]
cool

**Comment by Ticki** [comment]
:+1:

**Pull request merged**
