### PR TITLE
Start ox

### PR DESCRIPTION
**Pull request by Ticki**
Ox can now:

- Download package data
- Parse .oxp files

TODO:
- Verify signatures
- Install packages

### CODE REVIEW

**Comment by Ticki** [comment]
Btw, this PR also moves some files (to cargofy graphics module)

**Comment by hauleth** [comment]
I would move Ox to it's own repository. Finally it shouldn't be tied to this one OS and should be external binary. Monorepos aren't good IMHO.

**Comment by Ticki** [comment]
@hauleth Agree!

**Comment by hauleth** [comment]
This will also simplify access management as team @redox-os/package-management could have RW access to external repo and they will manage and discuss their design independently from Redox.

**Comment by jackpot51** [comment]
Creating ox repo, should it be redox-ox or ox? I think redox-os/ox would be good

**Comment by hauleth** [comment]
I think that it should be `redox-os/oxide`.

**Comment by jackpot51** [comment]
Thats good. Also, @hauleth did you get a slack invite?

**Comment by hauleth** [comment]
Yes. I've joined seconds ago.

**Comment by jackpot51** [comment]
Cool. The repo is up, hope @Ticki can make the first push and move the ox dir out of the kernel source

**Comment by hauleth** [comment]
To help with that I suggest using `git subtree`. I can do that if @Ticki doesn't want to.

**Comment by Ticki** [comment]
I will do ASAP.

**Pull request merged**
