### PR TITLE
Handle exceptional cases in the kernel, Use fewer raw pointers in the kernel, make Sodium react on Event::Close, Handle RSD signature statically, do not initialize unneeded variables, remove lots of warnings in the kernel, clean up coding style in `filesystem` and `kernel/syscall`, follow rust naming conventions more, general optimizations

### PR DESCRIPTION
**Pull request by Ticki**
Cleanup commits and actual changes are seperated

### CODE REVIEW

**Comment by Ticki** [comment]
> −666

I must be the devil.

**Comment by faizaanceg** [comment]
The title couldn't have been any more descriptive...

**Comment by Ticki** [comment]
> The title couldn't have been any more descriptive...

That's my weakness... Bad PR titles and bad commit messages. ;P

**Comment by polymetric1** [comment]
Jesus, that must be the longest PR title ever submitted.

**Comment by Ticki** [comment]
> Jesus, that must be the longest PR title ever submitted.

[Nah](https://github.com/redox-os/redox/pull/200)

**Comment by polymetric1** [comment]
This one better take up the whole page.

**Comment by polymetric1** [comment]
Good enough.

**Comment by Ticki** [comment]
[This one is actually longer.](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by polymetric1** [comment]
AAAAAA

**Comment by Ticki** [comment]
## #justinternetthings

**Comment by polymetric1** [comment]
that was genius. please never do that again lmao

**Pull request merged**
