### PR TITLE
Big code style cleanup (almost all .rs files cleaned up)

### PR DESCRIPTION
**Pull request by Ticki**

### CODE REVIEW

**Comment by jackpot51** [comment]
Ticki, can you get this to merge with master?

As a note, it is a very bad idea to continuously do style changes. I, for one, cannot follow all of these rules all the time, but that does not mean the code is unreadable.

Things I like:
- Spaces between function () and {
- Spacing out structs on one line per member

Some things I would not require as style:
- Commas after the last struct member? Many languages throw errors on this, like javascript, so it would be a very difficult rule to follow
- Putting function arguments on new lines. This should only be required if the function call is too long to read. In some places, this is absolutely unnecessary, like this code:
```
content.char(Point::new(8 * col, 16 * row),
                                 '_',
                                 Color::new(255, 255, 255));
```
Which, in my opinion, is better as this:
```
content.char(Point::new(8 * col, 16 * row),  '_', Color::new(255, 255, 255));
```

Many of these, then, should be developer decisions. We all have are own preferences, after all.

I definitely appreciate the cleanup, and early on, it is easier to take care of these issues. But if you have style items that will not be followed, I see it being a maintenance issue in the future.

**Comment by Ticki** [comment]
> Putting function arguments on new lines. This should only be required if the function call is too long to read. In some places, this is absolutely unnecessary, like this code:

I get this one. However:

> Commas after the last struct member? Many languages throw errors on this, like javascript, so it would be a very difficult rule to follow

I agree, if I should make this choice about Rust I would disallow it, however this is the convention in Rust, and I personally think that we should follow that. Thoughts?

**Comment by jackpot51** [comment]
If you get it to merge, this would change all of Redox to follow this convention, and I would start using a comma after the last struct member.

I would then be curious if we could count the number of violations of these concepts in a script. We could build a coding standard, and have a maximum line length to check for the function call seperation.

We could see how many violations of the comma rule there are and decide what to do then. We could also git blame the violations to see which contributors have which preferences.

What do you think? I like the cleanup, and think we need an automated way to check code style.

**Comment by jackpot51** [comment]
I think a new directory, tests/, could contain pass/fail scripts for the build system to run

**Comment by Ticki** [comment]
I could make a linter if you're interested.

**Comment by jackpot51** [comment]
That would be good. I'm going to push the tests folder in with an example

**Comment by tedsta** [comment]
Just thought I'd throw this out there: there is a code formatter for Rust in the works.

https://github.com/nrc/rustfmt

Not sure how usable it is yet.

**Comment by Ticki** [comment]
Merge conflict almost resolved.

**Comment by Ticki** [comment]
I'm giving up, I can't merge it.

**Comment by jackpot51** [comment]
Ticki, don't give up! If you have it half way, make another pull request with the conflicted files checked in and I can help you merge!

**Comment by jackpot51** [comment]
Hopefully, future style fixes won't have to touch as much code

**Comment by Ticki** [comment]
Yay! It's seems to be solved!

**Comment by jackpot51** [comment]
Good job Ticki!

**Comment by Ticki** [comment]
Will push ASAP.

**Comment by jackpot51** [comment]
Awesome, thanks

**Comment by Ticki** [comment]
Done.

**Comment by Ticki** [comment]
Should be mergable.

**Comment by Ticki** [comment]
Yay! It merged!

**Pull request merged**
